version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer selfupdate
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install --no-interaction
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: composer test
