version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-cli-node

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install --no-interaction

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: composer test
